dist: bionic
language: minimal
branches:
  only:
    - /^Uboot-.*$/
script:
  - make all
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - output/flash-image.bin
    - output/uart-images.tgz
  api_key: $GITHUB_TOKEN
  on:
    tags: true
    repo: vgist/catdrive
