dist: bionic
language: minimal
branches:
  only:
    - /^CatDrive-.*$/
addons:
  apt:
    packages:
      - bsdtar
      - tree
      - debootstrap
      - jq
      - binfmt-support
      - u-boot-tools
script:
  - make build_archlinux=y build_ubuntu=y build_debian=y build
  - tree -hn output
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: output/release/*.xz
  api_key: ${GITHUB_TOKEN}
  on:
    repo: vgist/catdrive
    tags: true
