dist: bionic
language: minimal
branches:
  only:
    - /^Kernel-4.*$/
addons:
  apt:
    packages:
      - tree
      - u-boot-tools
script:
  - make patch && make all
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - output/catdrive_defconfig
    - output/Image
    - output/modules.tar.xz
    - output/armada-3720-catdrive.dtb
  api_key: $GITHUB_TOKEN
  on:
    tags: true
    repo: vgist/catdrive
