name: uboot

on:
  push:
    tags:
      - Uboot-**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Initialize environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get install build-essential git tar xz-utils -y

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: uboot

    - name: Compile marvell
      run: |
        make all

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: output/*

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        files: output/*
